# ---

#- name: APT ; install libssl
#  become: true
#  apt:
#    deb: http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/{{ LIBSSL_DEB }}
#  register: apt_result
#  until: apt_result is not failed
#  retries: 30
#  delay: 10

# - name: APT_KEY ; add the irods key
#   become: true
#   ansible.builtin.apt_key:
#     url: https://packages.irods.org/irods-signing-key.asc
#     state: present
#   ignore_errors: true

# - name: APT_REPOSITORY | add the irods repo
#   become: true
#   ansible.builtin.apt_repository:
#     repo: "deb [arch=amd64] https://packages.irods.org/apt/ focal main"
#     state: present
#   ignore_errors: true

# - name: APT ; install irods-icommands
#   become: true
#   apt:
#     name: irods-icommands
#     state: present
#     update_cache: yes
#   register: apt_result
#   until: apt_result is not failed
#   retries: 10
#   delay: 10
#   ignore_errors: true
