---
- name: FILE ; ensure the share directory exists
  become: true
  file:
    path: "{{ SHARE_DIR }}"
    state: directory
    mode: '0750'
    
- name: APT ; install nfs-common
  become: true
  apt:
    pkg:
      - nfs-common
    state: present
    update_cache: yes
  register: apt_result
  until: apt_result is not failed
  retries: 30
  delay: 10

- name: MOUNT ; mount the nfs share
  become: true
  mount:
    src: 10.0.205.254:/ofo-share-serve
    fstype: nfs
    opts: timeo=14
    path: "{{ SHARE_DIR }}"
    state: mounted
    